name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Version Check"
        run: node -v

      - name: "Setup npm dependencies"
        run: npm install

      - name: "Build"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: npm run make

      - name: Upload Artifacts for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: |
            ./out/make/squirrel.windows/x64/*.exe
            ./out/make/squirrel.windows/x64/*.nupkg

      - name: Upload Artifacts for Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: |
            ./out/make/deb/x64/*.deb
            ./out/make/rpm/x64/*.rpm

      - name: Upload Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: MacOS
          path: |
            ./out/make/*.dmg
            ./out/make/zip/darwin/x64/*.zip